# Generated by Django 2.0 on 2017-12-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sidebar_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
