# Generated by Django 2.0 on 2017-12-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_sidebar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='div_id',
            field=models.CharField(default='notset', max_length=200),
            preserve_default=False,
        ),
    ]
