# Generated by Django 2.0 on 2017-12-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('start_date', models.CharField(default='', max_length=200)),
                ('end_date', models.CharField(default='', max_length=200)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('index', models.IntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honor_name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Education')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('collaborators', models.CharField(default='', max_length=200)),
                ('start_date', models.CharField(default='', max_length=200)),
                ('end_date', models.CharField(default='', max_length=200)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('index', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=200)),
                ('confidence', models.IntegerField()),
            ],
        ),
    ]
