# Generated by Django 2.0 on 2017-12-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20171227_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='order',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='order',
        ),
        migrations.RemoveField(
            model_name='experiencedescription',
            name='order',
        ),
        migrations.RemoveField(
            model_name='honor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.RemoveField(
            model_name='projectdescription',
            name='order',
        ),
    ]
